import {
  Injectable,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { IdGeneratorService } from '../utils/id-generator.service';
import { EventsGateway } from '../events/events.gateway';
import { CreateBillingDto } from './dto/create-billing.dto';
const Razorpay = require('razorpay');

@Injectable()
export class BillingService {
  constructor(
    private prisma: PrismaService,
    private idGenerator: IdGeneratorService,
    private eventsGateway: EventsGateway,
  ) {}

  /**
   * Create a new bill for an OPD visit.
   * - Auto-generates bill_number via IdGeneratorService
   * - total_amount is GENERATED by Postgres (subtotal + tax - discount)
   * - Always starts as payment_status: 'Pending', billing_status: 'Finalized'
   * - Auto-deducts medicine stock on creation
   */
  async create(dto: CreateBillingDto, userId: number) {
    const { hospital_id, visit_id, subtotal_amount, tax_amount, discount_amount, items } = dto;

    // Validate visit exists
    const visit = await this.prisma.opd_visits.findUnique({
      where: { opd_id: visit_id },
    });
    if (!visit) throw new NotFoundException('OPD Visit not found');

    // Generate bill number on the backend
    const billNumber = await this.idGenerator.generateBillNumber(hospital_id, userId);

    return this.prisma.$transaction(async (tx) => {
      // Create the bill (total_amount is computed by Postgres via dbgenerated)
      const bill = await tx.billing.create({
        data: {
          hospital_id,
          visit_id,
          bill_number: billNumber,
          subtotal_amount,
          tax_amount: tax_amount || 0,
          discount_amount: discount_amount || 0,
          // total_amount — NOT set; Postgres computes it via dbgenerated
          payment_status: 'Pending',
          billing_status: 'Finalized',
          created_by: userId,
          modified_by: userId,
          bill_items: {
            create: items.map((item) => ({
              item_type: item.item_type,
              reference_id: item.reference_id,
              item_description: item.item_description,
              quantity: item.quantity,
              unit_price: item.unit_price,
              total_price: item.total_price,
            })),
          },
        },
        include: {
          bill_items: true,
        },
      });

      // --- Stock Deduction moved to Pharmacy Module ---

      return bill;
    });
  }

  /**
   * Update bill items and amounts.
   * total_amount is NOT updated (Postgres GENERATED column).
   */
  async update(id: number, updateData: any, userId: number) {
    const { subtotal_amount, tax_amount, discount_amount, payment_status, items } =
      updateData;

    // Update items if passed
    if (items && items.length > 0) {
      await this.prisma.$transaction(async (tx) => {
        await tx.bill_items.deleteMany({ where: { bill_id: id } });
        await tx.bill_items.createMany({
          data: items.map((item) => ({
            bill_id: id,
            item_type: item.item_type || 'Other',
            reference_id: item.reference_id ? Number(item.reference_id) : null,
            item_description: item.item_description || 'Item',
            quantity: item.quantity || 1,
            unit_price: item.unit_price || 0,
            total_price: item.total_price || 0,
          })),
        });
      });
    }

    const updatePayload: any = {
      modified_by: userId,
      modified_at: new Date(),
    };
    if (subtotal_amount !== undefined)
      updatePayload.subtotal_amount = subtotal_amount;
    if (tax_amount !== undefined) updatePayload.tax_amount = tax_amount;
    if (discount_amount !== undefined)
      updatePayload.discount_amount = discount_amount;
    // DO NOT set total_amount — it is GENERATED by Postgres
    if (payment_status !== undefined)
      updatePayload.payment_status = payment_status;

    return this.prisma.billing.update({
      where: { bill_id: id },
      data: updatePayload,
      include: { bill_items: true },
    });
  }

  /**
   * Record a payment against a bill.
   * Calculates cumulative paid amount to determine if bill is fully paid.
   */
  async payBill(id: number, paymentData: any, userId: number) {
    const { payment_mode_id, amount_paid, reference_number } = paymentData;

    const bill = await this.prisma.billing.findUnique({
      where: { bill_id: id },
      include: { payments: true },
    });
    if (!bill) throw new NotFoundException('Bill not found');

    // Calculate cumulative paid so far
    const existingPaid = bill.payments
      .filter((p) => p.payment_status === 'Success')
      .reduce((sum, p) => sum + Number(p.amount_paid), 0);

    const newPaymentAmount = paymentData.amount_paid !== undefined && paymentData.amount_paid !== null 
      ? Number(paymentData.amount_paid) 
      : Number(bill.total_amount) - existingPaid;

    // Create payment record
    await this.prisma.payments.create({
      data: {
        bill_id: id,
        payment_mode_id: Number(payment_mode_id) || 1,
        amount_paid: newPaymentAmount,
        reference_number: reference_number || null,
        payment_status: 'Success',
        received_by: userId,
        created_by: userId,
        modified_by: userId,
      },
    });

    // Determine new payment status
    const totalPaid = existingPaid + newPaymentAmount;
    const billTotal = Number(bill.total_amount);
    
    let newStatus = totalPaid >= billTotal ? 'Paid' : 'Partially Paid';
    // If Insurance Claim (ID 6), mark as Insurance Pending regardless of amount paid
    if (Number(payment_mode_id) === 6) {
      newStatus = 'Insurance Pending';
    }

    // Update billing payment status
    return this.prisma.billing.update({
      where: { bill_id: id },
      data: { payment_status: newStatus, modified_by: userId },
      include: {
        bill_items: true,
        payments: {
          include: { payment_modes: true },
        },
      },
    });
  }

  /**
   * Find all bills for a specific visit.
   */
  async findByVisit(visit_id: number) {
    return this.prisma.billing.findMany({
      where: { visit_id },
      include: {
        bill_items: true,
        payments: {
          include: { payment_modes: true },
        },
      },
    });
  }

  /**
   * Find a single bill by ID with full details.
   */
  async findOne(id: number) {
    const bill = await this.prisma.billing.findUnique({
      where: { bill_id: id },
      include: {
        hospitals: true,
        bill_items: true,
        payments: {
          include: { payment_modes: true },
        },
        opd_visits: {
          include: { 
            patients: {
              include: { users_patients_user_idTousers: true }
            }, 
            doctors: true 
          },
        },
      },
    });
    if (!bill) throw new NotFoundException('Bill not found');

    const successfulPayments = bill.payments.filter((p) => p.payment_status === 'Success');
    const latestPayment = successfulPayments.length > 0 ? successfulPayments[successfulPayments.length - 1] : null;

    return {
      ...bill,
      patientName: bill.opd_visits?.patients?.users_patients_user_idTousers?.full_name || 'Unknown',
      patientid: bill.opd_visits?.patient_id,
      paymentModeName: latestPayment?.payment_modes?.payment_mode_name || null,
    };
  }

  /**
   * List all bills with filters.
   * Status filter uses payment_status (Paid/Pending/Partially Paid).
   */
  async findAll(query: any) {
    const { hospital_id, patient_id, patient_user_id, visit_id, status } =
      query;
    const where: any = {};

    if (hospital_id) where.hospital_id = +hospital_id;
    if (visit_id) where.visit_id = +visit_id;

    // FIX: filter on payment_status, not billing_status
    if (status && status !== 'All') where.payment_status = status;

    if (patient_id) {
      where.opd_visits = {
        ...where.opd_visits,
        patient_id: +patient_id,
      };
    }

    if (patient_user_id) {
      where.opd_visits = {
        ...where.opd_visits,
        patients: {
          user_id: +patient_user_id,
        },
      };
    }

    const bills = await this.prisma.billing.findMany({
      where,
      include: {
        hospitals: true,
        bill_items: true,
        payments: {
          include: { payment_modes: true },
        },
        opd_visits: {
          select: {
            patients: {
              include: {
                users_patients_user_idTousers: { select: { full_name: true } },
              },
            },
            patient_id: true,
          },
        },
      },
      orderBy: { created_at: 'desc' },
    });

    return bills.map((b) => {
      // Get the latest successful payment's mode name
      const successfulPayments = b.payments.filter(
        (p) => p.payment_status === 'Success',
      );
      const latestPayment =
        successfulPayments.length > 0
          ? successfulPayments[successfulPayments.length - 1]
          : null;

      return {
        ...b,
        patientName:
          b.opd_visits?.patients?.users_patients_user_idTousers?.full_name ||
          'Unknown',
        patientid: b.opd_visits?.patient_id,
        paymentModeName:
          latestPayment?.payment_modes?.payment_mode_name || null,
      };
    });
  }

  /**
   * Create Razorpay Order
   */
  async createRazorpayOrder(id: number, amountPaid: number) {
    const bill = await this.prisma.billing.findUnique({
      where: { bill_id: id },
    });
    if (!bill) throw new NotFoundException('Bill not found');

    const amountToPay = amountPaid ? Number(amountPaid) : Number(bill.total_amount);

    const razorpay = new Razorpay({
      key_id: process.env.RAZORPAY_KEY_ID || 'dummy_key_id',
      key_secret: process.env.RAZORPAY_KEY_SECRET || 'dummy_key_secret',
    });

    const options = {
      amount: Math.round(amountToPay * 100), // amount in the smallest currency unit (paise)
      currency: 'INR',
      receipt: `receipt_bill_${id}`,
    };

    try {
      const order = await razorpay.orders.create(options);
      return { order_id: order.id, amount: options.amount, currency: options.currency };
    } catch (error) {
      console.error('Razorpay order creation failed', error);
      throw new BadRequestException('Failed to create Razorpay order');
    }
  }
}
